# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluonDataStructures.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63luonDataStructures.proto\"=\n\x14\x63luon_data_TimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x11\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x11\"\xd2\x01\n\x13\x63luon_data_Envelope\x12\x10\n\x08\x64\x61taType\x18\x01 \x01(\x11\x12\x16\n\x0eserializedData\x18\x02 \x01(\x0c\x12#\n\x04sent\x18\x03 \x01(\x0b\x32\x15.cluon_data_TimeStamp\x12\'\n\x08received\x18\x04 \x01(\x0b\x32\x15.cluon_data_TimeStamp\x12.\n\x0fsampleTimeStamp\x18\x05 \x01(\x0b\x32\x15.cluon_data_TimeStamp\x12\x13\n\x0bsenderStamp\x18\x06 \x01(\r\";\n\x18\x63luon_data_PlayerCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\r\x12\x0e\n\x06seekTo\x18\x02 \x01(\x02\"b\n\x17\x63luon_data_PlayerStatus\x12\r\n\x05state\x18\x01 \x01(\r\x12\x17\n\x0fnumberOfEntries\x18\x02 \x01(\r\x12\x1f\n\x17\x63urrentEntryForPlayback\x18\x03 \x01(\r\"-\n\x1a\x63luon_data_RecorderCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluonDataStructures_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLUON_DATA_TIMESTAMP']._serialized_start=29
  _globals['_CLUON_DATA_TIMESTAMP']._serialized_end=90
  _globals['_CLUON_DATA_ENVELOPE']._serialized_start=93
  _globals['_CLUON_DATA_ENVELOPE']._serialized_end=303
  _globals['_CLUON_DATA_PLAYERCOMMAND']._serialized_start=305
  _globals['_CLUON_DATA_PLAYERCOMMAND']._serialized_end=364
  _globals['_CLUON_DATA_PLAYERSTATUS']._serialized_start=366
  _globals['_CLUON_DATA_PLAYERSTATUS']._serialized_end=464
  _globals['_CLUON_DATA_RECORDERCOMMAND']._serialized_start=466
  _globals['_CLUON_DATA_RECORDERCOMMAND']._serialized_end=511
# @@protoc_insertion_point(module_scope)
